"""
blazer — Rust-powered DataFrame engine for Python.

Quickstart::

    import blazer

    df = blazer.read_parquet("/data/sales.parquet")
    result = (
        df.lazy()
          .filter(blazer.col("amount") > 100)
          .group_by(
              [blazer.col("region")],
              [blazer.col("amount").sum().alias("total")],
          )
          .sort("total", descending=True)
          .collect()
    )
    print(result)
"""

from __future__ import annotations

from typing import Union

# ---------------------------------------------------------------------------
# Scalar type accepted wherever an Expr or literal is expected
# ---------------------------------------------------------------------------
_Scalar = Union["Expr", int, float, str, bool]

# ---------------------------------------------------------------------------
# Expr
# ---------------------------------------------------------------------------

class Expr:
    """A lazy expression over one or more DataFrame columns."""

    # Naming
    def alias(self, name: str) -> "Expr": ...

    # Aggregations
    def sum(self)      -> "Expr": ...
    def mean(self)     -> "Expr": ...
    def min(self)      -> "Expr": ...
    def max(self)      -> "Expr": ...
    def count(self)    -> "Expr": ...
    def n_unique(self) -> "Expr": ...
    def first(self)    -> "Expr": ...
    def last(self)     -> "Expr": ...

    # Comparison
    def __gt__(self, other: _Scalar) -> "Expr": ...
    def __lt__(self, other: _Scalar) -> "Expr": ...
    def __eq__(self, other: _Scalar) -> "Expr": ...  # type: ignore[override]
    def __ne__(self, other: _Scalar) -> "Expr": ...  # type: ignore[override]
    def __le__(self, other: _Scalar) -> "Expr": ...
    def __ge__(self, other: _Scalar) -> "Expr": ...

    # Arithmetic
    def __add__(self,  other: _Scalar) -> "Expr": ...
    def __radd__(self, other: _Scalar) -> "Expr": ...
    def __sub__(self,  other: _Scalar) -> "Expr": ...
    def __rsub__(self, other: _Scalar) -> "Expr": ...
    def __mul__(self,  other: _Scalar) -> "Expr": ...
    def __rmul__(self, other: _Scalar) -> "Expr": ...
    def __truediv__(self, other: _Scalar) -> "Expr": ...

    # Logical
    def __and__(self,    other: "Expr") -> "Expr": ...
    def __or__(self,     other: "Expr") -> "Expr": ...
    def __invert__(self)                -> "Expr": ...

    # Null checks
    def is_null(self)     -> "Expr": ...
    def is_not_null(self) -> "Expr": ...

    # Type casting
    def cast(self, dtype: str) -> "Expr":
        """Cast to *dtype*.

        Accepted values: ``"Boolean"``, ``"Int8"``, ``"Int16"``, ``"Int32"``,
        ``"Int64"``, ``"UInt8"``, ``"UInt16"``, ``"UInt32"``, ``"UInt64"``,
        ``"Float32"``, ``"Float64"``, ``"Utf8"``.
        """
        ...

    # Window / rolling
    def over(self, partition_by: list["Expr"]) -> "Expr":
        """Broadcast an aggregate over partitions (window function)."""
        ...
    def rolling_mean(self, window_size: int) -> "Expr": ...

    # String helpers
    def str_contains(self,    pattern: str) -> "Expr": ...
    def str_starts_with(self, prefix:  str) -> "Expr": ...
    def str_ends_with(self,   suffix:  str) -> "Expr": ...
    def str_to_uppercase(self) -> "Expr": ...
    def str_to_lowercase(self) -> "Expr": ...

    def __repr__(self) -> str: ...
    def __str__(self)  -> str: ...


# ---------------------------------------------------------------------------
# DataFrame
# ---------------------------------------------------------------------------

class DataFrame:
    """An immutable, columnar in-memory table.

    Construct from a dict of lists::

        df = blazer.DataFrame({"x": [1, 2, 3], "y": [4.0, 5.0, 6.0]})

    Or read from a file::

        df = blazer.read_parquet("/data/file.parquet")
        df = blazer.read_csv("/data/file.csv")
    """

    def __init__(self, data: dict[str, list]) -> None: ...
    def height(self)  -> int: ...
    def width(self)   -> int: ...
    def __len__(self) -> int: ...
    def columns(self) -> list[str]: ...
    def schema(self)  -> list[dict[str, str]]:
        """Return ``[{"name": "col", "dtype": "Int64"}, ...]``."""
        ...

    def head(self, n: int = 5) -> "DataFrame": ...
    def tail(self, n: int = 5) -> "DataFrame": ...

    def sort(self, by: str, descending: bool = False) -> "DataFrame": ...
    def select_columns(self, names: list[str])        -> "DataFrame": ...
    def vstack(self, other: "DataFrame")              -> "DataFrame": ...

    def to_dict(self) -> dict[str, list]: ...

    def lazy(self) -> "LazyFrame": ...

    def write_parquet(self, path: str) -> int:
        """Write to Parquet; returns number of rows written."""
        ...
    def write_csv(self, path: str) -> int:
        """Write to CSV; returns number of rows written."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self)  -> str: ...


# ---------------------------------------------------------------------------
# LazyFrame
# ---------------------------------------------------------------------------

class LazyFrame:
    """A lazy query plan. Nothing executes until ``.collect()`` is called.

    Example::

        result = (
            blazer.scan_parquet("/data/events.parquet")
                .filter(blazer.col("ts") > blazer.lit(1_700_000_000))
                .select([blazer.col("user_id"), blazer.col("event")])
                .limit(1000)
                .collect()
        )
    """

    def filter(self,       predicate: Expr)                      -> "LazyFrame": ...
    def select(self,       exprs: list[Expr])                    -> "LazyFrame": ...
    def with_columns(self, exprs: list[Expr])                    -> "LazyFrame": ...
    def sort(self,         by: str, descending: bool = False)    -> "LazyFrame": ...
    def limit(self,        n: int)                               -> "LazyFrame": ...
    def distinct(self)                                           -> "LazyFrame": ...

    def group_by(self, keys: list[Expr], aggs: list[Expr]) -> "LazyFrame":
        """Group by *keys* and aggregate with *aggs*."""
        ...

    def join(
        self,
        other:    "LazyFrame",
        left_on:  list[Expr],
        right_on: list[Expr],
        how:      str = "inner",
    ) -> "LazyFrame":
        """Join with *other*.

        *how* must be one of ``"inner"`` (default), ``"left"``, ``"right"``,
        ``"outer"``, or ``"cross"``.
        """
        ...

    def with_streaming_budget(self, bytes: int) -> "LazyFrame":
        """Set the RAM budget (bytes) for the streaming engine."""
        ...

    def collect(self)            -> DataFrame: ...
    def collect_streaming(self)  -> DataFrame: ...

    def sink_parquet(self, path: str) -> int:
        """Stream results to a Parquet file; returns rows written."""
        ...
    def sink_csv(self, path: str) -> int:
        """Stream results to a CSV file; returns rows written."""
        ...

    def explain(self,           optimized: bool = True) -> str: ...
    def explain_streaming(self)                         -> str: ...

    def __repr__(self) -> str: ...


# ---------------------------------------------------------------------------
# Module-level functions
# ---------------------------------------------------------------------------

def col(name: str) -> Expr:
    """Reference a column by name: ``col("price")``."""
    ...

def lit(value: Union[int, float, str, bool]) -> Expr:
    """Wrap a Python scalar as a literal expression."""
    ...

def read_parquet(path: str) -> DataFrame:
    """Read an entire Parquet file (or single-file path) into memory."""
    ...

def scan_parquet(path: str) -> LazyFrame:
    """Lazily scan a Parquet file or directory. Reads nothing until
    ``.collect()`` is called."""
    ...

def read_csv(path: str) -> DataFrame:
    """Read an entire CSV file into memory."""
    ...

def scan_csv(path: str) -> LazyFrame:
    """Lazily scan a CSV file. Reads nothing until ``.collect()`` is
    called."""
    ...
